### ISSUE TITLE
Feedback on pyslitmask

### ISSUE THREAD

**Issue by crawfordsm** [saltastro/pysalt#97]
- could only run the command line version on astro

- I couldn’t copy and paste anything into the text boxes, which meant that if I wanted to put in a long target name or new centre coordinates I had to type them in by hand, for example.
- I have my own region file showing all my possible targets in different colours for different priorities, and could load that into ds9, but as soon as I clicked onto the slits or reference star tabs the ds9 window updated and removed my regions, so I had to keep reloading them.
- I had slit widths of 2 arcseconds as an additional column for all the galaxies in my catalogue, but that didn’t seem to load - the slit widths stayed the default 1.5 arcseconds.
- Even after clicking on optimize there were slit collsions, so the resulting mask wouldn’t be usable. It seemed to work when the position angle was zero.
- on trying to save, with ‘Write .rsmt file’ I got a segmentation error

writing xml...
writing with image
running finderchart Slitmask.xml /home/ros/SALT/proposals/2015-1_phase2/frame-r-002379-6-0093.fits Slitmask.png
WARNING: AstropyDeprecationWarning: The wcs_sky2pix function is deprecated and may be removed in a future version.
        Use wcs_world2pix instead. [astropy.utils.misc]
Finished writing rsmt file
Segmentation fault

And on trying ‘Create finder chart from current image’ I got a different error but it also crashed:
writing xml...
running finderchart tmprsmttmp.xml /home/ros/SALT/proposals/2015-1_phase2/frame-r-002379-6-0093.fits /home/ros/SALT/proposals/2015-1_phase2/finderchart_test
WARNING: AstropyDeprecationWarning: The wcs_sky2pix function is deprecated and may be removed in a future version.
        Use wcs_world2pix instead. [astropy.utils.misc]
Traceback (most recent call last):
  File "/salt/iraf/pysalt/proptools/finalizetab.py", line 213, in writeFC_Current
    self.writeFC(image=self.inimage)
  File "/salt/iraf/pysalt/proptools/finalizetab.py", line 245, in writeFC
    finderchart(xmlfile, image=image, outfile=self.fcfile)
  File "/salt/iraf/pysalt/proptools/finder_chart.py", line 203, in finderchart
    plot.save(str(outfile))
  File "/usr/local/lib/python2.6/dist-packages/APLpy-0.9.11-py2.6.egg/aplpy/aplpy.py", line 1580, in save
    self._figure.savefig(filename, dpi=dpi, transparent=transparent, bbox_inches='tight', bbox_extra_artists=artists, format=format)
  File "/usr/local/lib/python2.6/dist-packages/matplotlib/figure.py", line 1185, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/usr/local/lib/python2.6/dist-packages/matplotlib/backend_bases.py", line 1947, in print_figure
    print_method = self._get_print_method(format)
  File "/usr/local/lib/python2.6/dist-packages/matplotlib/backend_bases.py", line 1887, in _get_print_method
    '%s.' % (format, ', '.join(formats)))
ValueError: Format "" is not supported.
Supported formats: emf, eps, jpeg, jpg, pdf, png, ps, raw, rgba, svg, svgz, tif, tiff.
Segmentation fault

**Comment by crawfordsm** [comment]
cc: @dr-jpk

**Comment by crawfordsm** [comment]
First object not showing up in the catalog

**Comment by crawfordsm** [comment]
* iraf was being used instead of pyraf but it would be helpful to add information about how to start it from the command line (either via pyraf or a script)

* copy and pasting may be related to logging in remote from a mac to linux server. 

* slitwidths is a bug and needs to be fixed

* region file is a feature request to add identify all the slits from a ds9 region file loaded into the ds9 or from the GUI

* optimization was broken and throwing an error

* seg fault was not reproducible

**Comment by crawfordsm** [comment]
* More information from the output of the optimization (like total weight)

* info or tool tip added to optimize page for y-spacing
